server:
  port: 8065

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/baseBackFinal
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

rabbitmq:
  queue:
    movies:
      name: moviesQueue
    series:
      name: seriesQueue
  exchange: exchange
  routingkey: routingkey

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      showDetails: always

