server:
  port : 8097
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/baseBackFinal
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

 rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange: rabbitmq.exchange
    routingkey: rabbitmq.routingkey

rabbitmq:
  queue:
    movie:
      name: movieQueue
  exchange: exchange
  routingkey: routingkey

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      movies:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movies:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
#          - feign.FeignException$InternalServerError
          - java.lang.Exception
