server:
  port : 8085
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: 27042001
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  sql:
    init:
      dataLocations: classPath:/games_service.sql  
  application:
    name: movieservice

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
